---
- hosts: '{{host}}'
  become: yes

  tasks:
   #- include_vars: user_list_security_active-test.yml
   - include_vars: "{{ userlist }}.yml"

   - yum: pkg=nmap-ncat state=present
   - yum: pkg=screen state=present
   - yum: pkg=nmap state=present
   
   - group: name=secops state=present gid=2004

   - name: Create login for '{{users}}'
     #user: name={{user}} generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa group=sysops
     user: name={{ item.username }} shell=/bin/bash createhome=yes comment='create with ansible' groups={{ item.groups }}
     with_items: '{{users}}'

   - name: Setup | authorized key upload
     authorized_key: user={{ item.username }}
      key="{{ lookup('file', '/Users/hchan/gitrepo/aws-infrastructure/mm-manage-user/public_keys/{{ item.username }}.authorized_keys') }}"
       path='/home/{{ item.username }}/.ssh/authorized_keys'
   #   manage_dir=no
     with_items: '{{users}}'

   - name: Sudoers | update sudoers file and validate
     lineinfile: "dest=/etc/sudoers
	insertafter=EOF
	line='%secops  ALL=(ALL) NOPASSWD:/bin/nc, /bin/ncat, /usr/sbin/lsof, /usr/bin/docker'
	regexp='^%secops'
 	state=present"
     when: '{{ item.use_sudo }} == True'
     with_items: '{{users}}'
